jobs:
- job: PrintHostDetails
  displayName: 'Print Host Details'
  pool:
    name: 'Default'
  steps:
  - script: |
      echo "Host Details:"
      echo "Hostname: $(hostname)"
      echo "Operating System: $(uname -a)"
      echo "CPU Information: $(lscpu)"
      echo "Memory Information: $(free -h)"
    displayName: 'Print Host Details'

- job: Print_Details_From_Shell_Script
  displayName: Print Details From Shell Script
  pool:
    name: 'Default'
  steps:
  - script: |
      ./script.sh
